Remove nstar codec definition
esrlabs/northstar pull request #200
Opened 2020-11-17 13:40 UTC by alfonsoros88

This changes intends to simplify a bit `nstar`'s  source by removing the
codec definition to serialize messages.

2020-11-17 14:00 UTC, flxo requested changes

2020-11-17 14:00 UTC, flxo commented on nstar/src/main.rs
> +        let mut framed_read = tokio_util::codec::FramedRead::new(read, LengthDelimitedCodec::new());
Map the stream to `api::Message` to have the deserialisation at only one place.

2020-11-17 14:05 UTC, alfonsoros88 commented on nstar/src/main.rs
> +                                            Ok(b) => match framed_write.send(b).await {
whoops, I overlooked that. Will close this pr.

2020-11-17 14:07 UTC, flxo commented
Think we can fix that :-)

2020-12-10 07:36 UTC, marcmo commented
@flxo do we still want to pursue this PR?

2020-12-16 16:09 UTC, flxo commented
> @flxo do we still want to pursue this PR?

I have some more things for the codec in the pipeline for the quiets christmas days. I like the codec idea because it can be reused but the TCP stream part is tricky. Let's close this here.

2020-12-16 16:09 UTC, closed without merging