Remove unshare_root workaround
esrlabs/northstar pull request #310
Opened 2021-03-09 16:14 UTC by marcmo

by introducing a bind-mount of the run-dir
and marking the mount propagation for that one as private

2021-03-09 16:16 UTC, marcmo commented
Not sure that is all. Running on my machine the mount is not visible to other processes.
tests are now broken but first wanted to get some feedback from @flxo

2021-03-09 16:52 UTC, flxo commented
@marcmo The tests fail with:

```
The application panicked (crashed).
956
Message:  Test failed: 
957
   0: Failed to remove tmpdir
958
   1: Device or resource busy (os error 16) at path "/tmp/.tmpOnsgZJ"
```

This is because the bind mount is not umounted upon shutdown. This missing  when the runtime task breaks.

2021-03-10 10:25 UTC, flxo requested changes

2021-03-10 10:25 UTC, flxo commented on northstar/src/main.rs
> -        // Set the mount propagation of unshare_root to MS_PRIVATE
This needs to be remove from integration_tests::macros.rs as well

2021-03-10 10:25 UTC, flxo commented on northstar_tests/src/runtime.rs
> -                unshare_root: PathBuf::from("/"),
The `unshare_root` is in the example northstar.toml. Think we should add `#[serde(deny_unknown_fields)]` to not allow unknown fields in all struct in `config.rs`.

2021-03-26 12:25 UTC, merged